apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 831926614723.dkr.ecr.ap-northeast-2.amazonaws.com/instagram-server
  newName: 831926614723.dkr.ecr.ap-northeast-2.amazonaws.com/instagram-server
  newTag: 8e479ac0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
