name: Deploy To EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 내부망에서 실행

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io
      #     sudo systemctl start docker
      #     sudo systemctl enable docker

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Check Docker Version
        run: docker version
       
      # - name: Docker 이미지 생성
      #   run: docker build -t instagram-server .

      # - name: Docker 이미지에 Tag 붙이기
      #   run: docker tag instagram-server ${{ steps.login-ecr.outputs.registry }}/instagram-server:latest

      # - name: ECR에 Docker 이미지 Push하기
      #   run: docker push ${{ steps.login-ecr.outputs.registry }}/instagram-server:latest
      
      - name: 이미지 태그 (버전)
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      - name: ECR에 build, tag, push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: instagram-server
          IMAGE_TAG: ${{ steps.image.outputs.version }}
        run: |
          echo "::set-output name=ecr_repository::$ECR_REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        
      
      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          repository: InTaewoo/k8s-manifest-repo
          ref: master
          token: ${{ secrets.ACTION_TOKEN }}
          path: k8s-manifest-repo
    
      - name: Update Kubernetes resources
        run: |
          echo ${{ steps.login-ecr.outputs.registry }}
          echo ${{ steps.image-info.outputs.ecr_repository }}
          echo ${{ steps.image.outputs.version }}
          cd k8s-manifest-repo/overlays/dev/
          kustomize edit set image ${{ steps.login-ecr.outputs.registry }}/instagram-server=${{ steps.login-ecr.outputs.registry }}/instagram-server:${{ steps.image.outputs.version }}
          cat kustomization.yaml
    
      - name: Commit files
        run: |
          cd k8s-manifest-repo
          git config --global user.email "oilehot0910@naver.com"
          git config --global user.name "Intaewoo"
          git commit -m "Update image tag"
          git push -u origin master